/*
 * This source file was generated by the Gradle 'init' task
 */
package project.sync;

import project.sync.Service.FileReceiver;
import project.sync.Service.FileSender;
import project.sync.Service.FileWatcher;

public class AppA {

    public static void main(String[] args) throws Exception {
        String folderPath = "D:\\Sycn A";
        String host = "127.0.0.1";
        int myPort = 5000;
        int targetPort = 5001;

        new Thread(() -> {
            try {
                new FileReceiver(myPort, folderPath).start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

        FileSender sender = new FileSender(host, targetPort);
        new FileWatcher(folderPath, sender).start();
    }

}
